environment         = "stg"
aws_region          = "eu-west-1"
project_name        = "ro-sports-club-stg"
aws_profile         = "603825719481_AdministratorAccess"
s3_bucket_name      = "ro-terraform-state-bucket"
dynamodb_table_name = "ro-terraform-state-lock"
