environment    = "dev"
SQS_queue_name = "order-events"
runtime        = "nodejs22.x"
aws_region     = "eu-west-1"
project_name   = "ro-sports-club-dev"
aws_profile    = "603825719481_AdministratorAccess"
